### ISSUE TITLE
Can't seem to open the menu

### ISSUE THREAD

**Issue by NPCIsaac** [DanielMatrixSYS/Sublime-Levels#20]
Hello, I've tried this addon on my server today and it works but I can't seem to open the menu? could I get some help please.

**Comment by DanielMatrixSYS** [comment]
Hi!

To open the menu you have to press _**F6**_ or type _**!slevels**_ in chat. Do none of these work for you? What are the clientside/serverside errors you're getting?

**Comment by NPCIsaac** [comment]
I'm not getting any errors, which is weird 

so i'm not sure why it's not appearing, i subscribed to the addon.
